language: csharp
solution: MamaBird.sln
sudo: required
dist: trusty

mono: none
dotnet: 2.0.0
branches:
  only:
    - master

script: 
  - dotnet restore
  - dotnet build -c Release
  - dotnet test MamaBird.Test/MamaBird.Test.csproj