language: csharp
solution: MamaBird.sln
sudo: required
dist: trusty

mono: none
dotnet: 2.0.0

script: 
  - dotnet restore
  - dotnet build -c Release
  - dotnet test MamaBird.Test/MamaBird.Test.csproj -p:ParallelizeTestCollections=false