languag: csharp
solution: MamaBird.sln
sudo: required
dist: trusty

mono: none
dotnet: 2.1.103
branches:
  only:
    - master
    
install:
  - dotnet restore
script: 
  - dotnet build 
  - dotnet test MamaBird.Test/MamaBird.Test.csproj