version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies:
    only:
    - .\MamaBird.Test\MamaBird.Test.csproj
deploy:
- provider: NuGet
  api_key:
    secure: w5bF0sAFDRh8GarN8MgQiG/f8k1D3A9uiSVIWGRJio2w4qipLItnqD0CySMKeUQq
  on:
    branch: master
    appveyor_repo_tag: true
- provider: NuGet
  server: https://www.myget.org/F/robertruetz-ci/api/v2/package
  api_key:
    secure: KvkY4kOsTXyIRHqJfrjVA2dV/VQ8cwh/LrQzIO0Bc6RWoUcx0KfIssL0gXACYfOObmxcAcJwmoliOiXHZMEy1WN1nAajzPR44jcNuBoXS/jvS775KIpHb0r9xW1Nq4ii5aNmMJed1Hiy5HHwxAHn5gAlmODuRr7hhpGkUck0g3xgIffofkJI24zVYqpKHFOG
  on:
    branch: master